---
- name: Create faucet group
  group:
    name: faucet
    system: yes
    state: present

- name: Create faucet user
  user:
    name: faucet
    group: faucet
    createhome: no
    system: yes
    state: present

- name: Import oftr packaging GPG signing key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: FFBE06FBB4EDC679174DD2CCD5AA2ED445128570
    state: present

- name: Add oftr repository
  apt_repository:
    repo: "deb http://ppa.launchpad.net/byllyfish/oftr/ubuntu xenial main"
    state: present

- name: Install faucet-zof dependencies
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - python3
    - python3-pip
    - python3-dev
    - python3-pbr
    - python3-setuptools
    - oftr
    - git

- name: Install faucet-zof pip dependencies
  pip:
    name: "{{ item }}"
    executable: pip3
    state: latest
  with_items:
    - networkx
    - pyyaml
    - zof

- name: Install faucet-zof
  pip:
    name: git+https://github.com/byllyfish/faucet@port5#egg=faucet
    editable: false
    executable: pip3
    state: latest
  notify:
    - restart faucet-l2

- name: Add faucet-l2 defaults file
  copy:
    src: default-l2
    dest: /etc/default/faucet-l2

- name: Create faucet config directory
  file:
    path: /etc/ryu/faucet/
    owner: root
    group: root
    recurse: yes
    state: directory

- name: Create faucet log directory
  file:
    path: /var/log/ryu/faucet/
    owner: faucet
    group: faucet
    recurse: yes
    state: directory

- name: Add faucet logrotate config
  copy:
    src: logrotate
    dest: /etc/logrotate.d/faucet

- name: Add faucet-l2 systemd unit
  copy:
    src: faucet-l2.service
    dest: /etc/systemd/system/

- name: Enable faucet-l2 systemd unit
  systemd:
    name: faucet-l2
    daemon_reload: yes
    enabled: yes
    masked: no
    state: started

- name: Add common faucet configuration
  copy:
    src: faucet/common/
    dest: /etc/ryu/faucet/common/
  notify:
    - reload faucet-l2

- name: Add l2 configuration
  copy:
    src: faucet/l2/
    dest: /etc/ryu/faucet/l2/
  notify:
    - reload faucet-l2

- name: Add faucet-l2 configuration
  copy:
    src: faucet/faucet-l2.yaml
    dest: /etc/ryu/faucet/
  notify:
    - reload faucet-l2

- name: Add faucet-l2 TFM configuration
  copy:
    src: faucet/tfm/
    dest: /etc/ryu/faucet/
  notify:
    - restart faucet-l2
