---
- name: reload faucet-l3
  service:
    name: faucet-l3
    state: reloaded

- name: reload faucet-l2
  service:
    name: faucet-l2
    state: reloaded

- name: reload faucet-l2-secondary
  service:
    name: faucet-l2-secondary
    state: reloaded

- name: restart faucet-l3
  service:
    name: faucet-l3
    state: restarted

- name: restart faucet-l2
  service:
    name: faucet-l2
    state: restarted

- name: restart faucet-l2-secondary
  service:
    name: faucet-l2-secondary
    state: restarted
