---
- hosts: allbirds.wand.net.nz
  roles:
    - role: common
    - role: libvirt
    - role: ovs-dpdk-switch
- hosts: faucet.redcables.wand.nz
  roles:
    - role: bearwall
    - role: common
    - role: bird
    - role: dhcp
    - role: dhcpv6
    - role: faucet
    - role: freeradius
    - role: prometheus-node-exporter
    - role: unbound
- hosts: faucet-zof.redcables.wand.nz
  roles:
    - role: bearwall
    - role: common
    - role: faucet-zof
    - role: prometheus-node-exporter
- hosts: nat64.redcables.wand.nz
  roles:
    - role: bearwall
    - role: common
    - role: bird
    - role: dhcpv6
    - role: jool
    - role: prometheus-node-exporter
    - role: unbound
- hosts: monitoring.redcables.wand.nz
  roles:
    - role: bearwall
    - role: common
    - role: gauge
    - role: smokeping
    - role: prometheus
    - role: prometheus-node-exporter
    - role: prometheus-pushgateway
    - role: apache
- hosts: amp.redcables.wand.nz
  roles:
    - role: bearwall
    - role: common
    - role: apache
    - role: amp-server
    - role: amplet-lite
    - role: prometheus-node-exporter
- hosts: awdy.redcables.wand.nz
  roles:
    - role: bearwall
    - role: common
    - role: apache
    - role: awdy
    - role: prometheus-node-exporter
- hosts: builder-1.redcables.wand.nz
  roles:
    - role: bearwall
    - role: common
    - role: apache
    - role: prometheus-node-exporter
