---
- name: Install faucet dependencies
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - python3
    - python3-pip
    - python3-dev
    - python3-pbr
    - git

- name: Create faucet group
  group:
    name: faucet
    system: yes
    state: present

- name: Create faucet user
  user:
    name: faucet
    group: faucet
    createhome: no
    system: yes
    state: present

- name: Install faucet
  pip:
    name: faucet
    executable: pip3
    version: "{{ faucet_version }}"
    state: present
  notify:
    - restart faucet-l3
    - restart faucet-l2
    - restart faucet-l2-secondary

- name: Add faucet-l3 defaults file
  copy:
    src: default-l3
    dest: /etc/default/faucet-l3

- name: Add faucet-l2 defaults file
  copy:
    src: default-l2
    dest: /etc/default/faucet-l2

- name: Add faucet-l2-secondary defaults file
  copy:
    src: default-l2-secondary
    dest: /etc/default/faucet-l2-secondary

- name: Create faucet config directory
  file:
    path: /etc/faucet/
    owner: root
    group: root
    recurse: yes
    state: directory

- name: Configure ryu
  copy:
    src: ryu.conf
    dest: /etc/faucet/

- name: Create faucet log directory
  file:
    path: /var/log/faucet/
    owner: faucet
    group: faucet
    recurse: yes
    state: directory

- name: Add faucet logrotate config
  copy:
    src: logrotate
    dest: /etc/logrotate.d/faucet

- name: Add faucet systemd unit
  copy:
    src: faucet-l3.service
    dest: /etc/systemd/system/

- name: Add faucet-l2 systemd unit
  copy:
    src: faucet-l2.service
    dest: /etc/systemd/system/

- name: Add faucet-l2-secondary systemd unit
  copy:
    src: faucet-l2-secondary.service
    dest: /etc/systemd/system/

- name: Enable faucet systemd unit
  systemd:
    name: faucet-l3
    daemon_reload: yes
    enabled: yes
    masked: no
    state: started

- name: Enable faucet-l2 systemd unit
  systemd:
    name: faucet-l2
    daemon_reload: yes
    enabled: yes
    masked: no
    state: started

- name: Enable faucet-l2-secondary systemd unit
  systemd:
    name: faucet-l2-secondary
    daemon_reload: yes
    enabled: yes
    masked: no
    state: started

- name: Add common faucet configuration
  copy:
    src: faucet/common/
    dest: /etc/faucet/common/
  notify:
    - reload faucet-l3
    - reload faucet-l2
    - reload faucet-l2-secondary

- name: Add l2 configuration
  copy:
    src: faucet/l2/
    dest: /etc/faucet/l2/
  notify:
    - reload faucet-l2
    - reload faucet-l2-secondary

- name: Add faucet-l3 configuration
  copy:
    src: faucet/faucet-l3.yaml
    dest: /etc/faucet/
  notify:
    - reload faucet-l3

- name: Add faucet-l2 configuration
  copy:
    src: faucet/faucet-l2.yaml
    dest: /etc/faucet/
  notify:
    - reload faucet-l2
    - reload faucet-l2-secondary

- name: Check faucet-l3 config
  shell: check_faucet_config /etc/faucet/faucet-l3.yaml

- name: Check faucet-l2 config
  shell: check_faucet_config /etc/faucet/faucet-l2.yaml
