---
- name: Install gauge dependencies
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - git
    - python3
    - python3-pip
    - python3-venv
    - python3-setuptools
    - python3-dev
    - python3-pbr

- name: Create faucet group
  group:
    name: faucet
    system: yes
    state: present

- name: Create faucet user
  user:
    name: faucet
    group: faucet
    createhome: no
    system: yes
    state: present

- name: Create faucet python virtualenv directory
  file:
    path: /opt/faucet/venv
    state: directory
    owner: root
    group: root
    mode: "u=rwx,g=rx,o=rx"

- name: Install gauge in python virtualenv
  pip:
    name: faucet
    version: "{{ gauge_version }}"
    virtualenv: /opt/faucet/venv
    virtualenv_command: "/usr/bin/python3 -m venv"
    state: present
  notify: restart gauge

- name: Add gauge defaults file
  copy:
    src: default
    dest: /etc/default/gauge

- name: Create faucet config directory
  file:
    path: /etc/faucet/
    owner: root
    group: root
    recurse: yes
    state: directory

- name: Configure ryu
  copy:
    src: ryu.conf
    dest: /etc/faucet/

- name: Create gauge log directory
  file:
    path: /var/log/faucet/
    owner: faucet
    group: faucet
    recurse: yes
    state: directory

- name: Add gauge logrotate config
  copy:
    src: logrotate
    dest: /etc/logrotate.d/gauge

- name: Add gauge systemd unit
  copy:
    src: gauge.service
    dest: /etc/systemd/system/

- name: Enable gauge systemd unit
  systemd:
    name: gauge
    daemon_reload: yes
    enabled: yes
    masked: no
    state: started

- name: Configure gauge
  template:
    src: gauge.yaml.j2
    dest: /etc/faucet/gauge.yaml
  notify: restart gauge

- name: Add faucet configuration
  copy:
    src: faucet/
    dest: /etc/faucet/
  notify: restart gauge
