---
- name: Import wand packaging GPG signing key
  apt_key:
    url: https://packages.wand.net.nz/keyring.gpg
    state: present

- name: Add wand repository
  apt_repository:
    repo: "deb https://packages.wand.net.nz {{ansible_distribution_release}} ovs-2.12"
    state: present

- name: Install openvswitch-dpdk
  apt:
    name: openvswitch-switch-dpdk
    state: installed

- name: Disable irqbalance
  systemd:
    name: irqbalance
    masked: yes
    state: stopped

- name: Switch to userspace DPDK openvswitch
  alternatives:
    name: ovs-vswitchd
    path: /usr/lib/openvswitch-switch-dpdk/ovs-vswitchd-dpdk
  notify: restart openvswitch

- name: Make /dev/vfio executable to all
  file:
    path: /dev/vfio
    mode: a+x

- name: Set hugepages and iommu kernel settings
  lineinfile:
    dest: /etc/default/grub
    regexp: "^GRUB_CMDLINE_LINUX_DEFAULT="
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="default_hugepagesz=1G hugepagesz=1G hugepages=12 iommu=pt intel_iommu=on"'
    state: present
  notify: update grub

- name: Add hugepages mount point
  mount:
    name: /dev/hugepages
    src: nodev
    fstype: hugetlbfs
    opts: pagesize=1GB
    state: present

- name: Enable dpdk systemd unit
  systemd:
    name: dpdk
    daemon_reload: yes
    enabled: yes
    masked: no
    state: started

- name: Add dpdk configuration
  copy:
    src: dpdk/
    dest: /etc/dpdk/
  notify:
    - restart dpdk

- name: Add openvswitch systemd overrides
  copy:
    src: openvswitch-nonetwork.service.d/10-depend_on_dpdk.conf
    dest: /etc/systemd/system/openvswitch-nonetwork.service.d/
  notify: restart openvswitch with daemon-reload

- name: Set libvirt/qemu to run VMs as root so vhostuser ports work
  lineinfile:
    dest: /etc/libvirt/qemu.conf
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  with_items:
    - regexp: '^user.*='
      line: 'user = "root"'
    - regexp: '^group.*='
      line: 'group = "root"'
