---
- name: Uninstall prometheus package
  apt:
    name: prometheus
    purge: yes
    state: absent

- name: Create prometheus group
  group:
    name: prometheus
    system: yes
    state: present

- name: Create prometheus user
  user:
    name: prometheus
    group: prometheus
    createhome: no
    system: yes
    state: present

- name: Create prometheus install directory
  file:
    path: /opt/prometheus/prometheus
    owner: prometheus
    group: prometheus
    recurse: yes
    state: directory

- name: Create prometheus lib directory
  file:
    path: /var/lib/prometheus/metrics
    owner: prometheus
    group: prometheus
    recurse: yes
    state: directory

- name: Configure prometheus
  template:
    src: default
    dest: /etc/default/prometheus
  notify: restart prometheus

- name: Add prometheus configuration
  copy:
    src: prometheus/
    dest: /etc/prometheus/
  notify: restart prometheus

- name: Install prometheus
  unarchive:
    src: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: "/opt/prometheus/prometheus"
    extra_opts: "--strip-components=1"
    owner: prometheus
    group: prometheus
    remote_src: yes
  notify: restart prometheus

- name: Add prometheus systemd unit
  copy:
    src: prometheus.service
    dest: /etc/systemd/system/

- name: Enable prometheus systemd unit
  systemd:
    name: prometheus
    daemon_reload: yes
    enabled: yes
    masked: no
    state: started
