{
 "title": "Redcables Routing Tables",
 "tags": [ "FAUCET" ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "IPv4 Route Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(flow_packet_count_ipv4_fib{inst_count=\"2\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "IPv6 Route Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(flow_packet_count_ipv6_fib{inst_count=\"2\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "IPv4 FIB",
   "type": "table",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "label_replace(label_replace(flow_packet_count_ipv4_fib{inst_count=\"2\"}, 'vlan_vid', '', 'vlan_vid', '.*'), 'ipv4_dst', 'Default', 'ipv4_dst', '')",
     "legendFormat": "''"
    }
   ]
  },
  {
   "title": "IPv6 FIB",
   "type": "table",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "label_replace(label_replace(flow_packet_count_ipv6_fib{inst_count=\"2\"}, 'vlan_vid', '', 'vlan_vid', '.*'), 'ipv6_dst', 'Default', 'ipv6_dst', '')",
     "legendFormat": "''"
    }
   ]
  }
 ]
}